apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audito-ingress
  namespace: audito
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - audito.local
      secretName: audito-tls
  rules:
    - host: audito.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
