apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service
  namespace: audito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parsing-service
  template:
    metadata:
      labels:
        app: parsing-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: parsing-service-config
        image: yashhanamghar/audito-parsing-service:latest
        imagePullPolicy: Never
        name: parsing-service
        ports:
        - containerPort: 8006
        volumeMounts:
        - mountPath: /data/storage
          name: shared-storage-volume
      volumes:
      - name: shared-storage-volume
        persistentVolumeClaim:
          claimName: audito-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: parsing-service
  namespace: audito
spec:
  ports:
  - port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    app: parsing-service
  type: ClusterIP
