apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: audito
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          volumeMounts:
            - mountPath: /srv/storage
              name: shared-storage-volume
          image: postgres:16

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

            - name: POSTGRES_DB
              value: add_ai

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

      volumes:
        - name: shared-storage-volume
          persistentVolumeClaim:
            claimName: audito-shared-pvc
